[build]
  command = "npm run build"
  publish = "frontend"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_VERSION = "10.2.3"

[dev]
  command = "npm run dev"
  port = 8888

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
